"""Response types mirroring the Stophy OpenAPI schemas.

These are ``TypedDict``s with ``total=False`` - they describe the shape of the
JSON the API returns so editors and type checkers can help, without forcing
every optional/nullable field to be present.
"""

from __future__ import annotations

from typing import List, Literal, Optional, TypedDict, Union

CacheState = Literal["hit", "miss"]
ErrorCode = Literal[
    "UNAUTHORIZED",
    "INSUFFICIENT_CREDITS",
    "BAD_REQUEST",
    "INVALID_INPUT",
    "NOT_FOUND",
    "CONCURRENCY_LIMITED",
    "UPSTREAM_UNAVAILABLE",
    "INTERNAL_ERROR",
]
LiveChatStatus = Literal["live", "upcoming", "replay", "chat_disabled", "not_live"]


class Thumbnail(TypedDict, total=False):
    url: str
    width: int
    height: int


class EmptyState(TypedDict, total=False):
    code: str
    message: str


# --- transcript -----------------------------------------------------------
class TranscriptLanguage(TypedDict, total=False):
    code: Optional[str]
    name: Optional[str]
    isAutoGenerated: bool


class TranscriptSegment(TypedDict, total=False):
    start: float
    duration: float
    text: str


class TranscriptResult(TypedDict, total=False):
    language: TranscriptLanguage
    segments: List[TranscriptSegment]
    text: str
    empty: EmptyState


# --- video details --------------------------------------------------------
class VideoDetails(TypedDict, total=False):
    id: str
    type: Literal["video"]
    videoUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    category: Optional[str]
    description: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    isLive: bool
    likeCount: Optional[float]
    likeCountText: Optional[str]
    publishedAt: Optional[str]
    tags: List[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    thumbnails: List[Thumbnail]


class RelatedVideo(TypedDict, total=False):
    id: str
    type: Literal["video"]
    videoUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    thumbnails: List[Thumbnail]


class VideoDetailsData(TypedDict, total=False):
    video: VideoDetails
    related: List[RelatedVideo]


# --- comments / replies ---------------------------------------------------
class Comment(TypedDict, total=False):
    id: Optional[str]
    text: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    authorThumbnail: Optional[str]
    hasChannelOwnerReplied: bool
    isChannelOwner: bool
    isHearted: bool
    isPinned: bool
    isVerified: bool
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    likeCount: Optional[float]
    likeCountText: Optional[str]
    replyCount: Optional[float]
    replyCountText: Optional[str]
    repliesToken: Optional[str]


class CommentsData(TypedDict, total=False):
    videoId: str
    sortBy: Literal["any", "latest", "top"]
    items: List[Comment]
    continuationToken: Optional[str]
    empty: EmptyState


# --- live chat ------------------------------------------------------------
class LiveChatMessage(TypedDict, total=False):
    id: str
    text: str
    author: Optional[str]
    authorId: Optional[str]
    timestampUsec: Optional[str]
    isOwner: bool
    isModerator: bool
    isVerified: bool
    superChatAmount: Optional[str]
    superChatCurrency: Optional[str]


class LiveChatData(TypedDict, total=False):
    status: LiveChatStatus
    isLive: bool
    concurrentViewers: Optional[float]
    pollIntervalMs: Optional[float]
    messages: List[LiveChatMessage]
    continuationToken: Optional[str]


VideoData = Union[VideoDetailsData, TranscriptResult, CommentsData, LiveChatData]


# --- search ---------------------------------------------------------------
class SearchVideo(TypedDict, total=False):
    type: Literal["video"]
    id: str
    videoUrl: str
    title: str
    author: Optional[str]
    authorId: Optional[str]
    description: Optional[str]
    duration: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    isLive: bool
    isUpcoming: bool
    isVerified: bool
    viewCount: Optional[float]
    viewCountText: Optional[str]
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    thumbnails: List[Thumbnail]


class SearchShort(TypedDict, total=False):
    type: Literal["short"]
    id: str
    shortUrl: str
    title: str
    viewCount: Optional[float]
    viewCountText: Optional[str]
    thumbnails: List[Thumbnail]


class SearchPlaylist(TypedDict, total=False):
    type: Literal["playlist"]
    id: str
    playlistUrl: str
    title: str
    author: Optional[str]
    authorId: Optional[str]
    videoCount: Optional[float]
    videoCountText: Optional[str]
    thumbnails: List[Thumbnail]


class SearchChannel(TypedDict, total=False):
    type: Literal["channel"]
    id: str
    channelUrl: str
    name: str
    handle: Optional[str]
    description: Optional[str]
    subscriberCount: Optional[float]
    subscriberCountText: Optional[str]
    isVerified: bool
    thumbnails: List[Thumbnail]


SearchItem = Union[SearchVideo, SearchShort, SearchPlaylist, SearchChannel]


class SearchQuery(TypedDict, total=False):
    q: str
    type: Literal["video", "short", "channel", "playlist", "movie"]
    sortBy: Literal["relevance", "popularity", "date", "rating"]
    uploadDate: Literal["today", "week", "month", "year"]
    duration: Literal["short", "medium", "long"]
    features: List[str]


class SearchData(TypedDict, total=False):
    query: SearchQuery
    items: List[SearchItem]
    continuationToken: Optional[str]
    estimatedResults: int
    empty: EmptyState


# --- channel --------------------------------------------------------------
class ChannelLink(TypedDict, total=False):
    title: str
    url: str


class ChannelProfile(TypedDict, total=False):
    id: Optional[str]
    name: Optional[str]
    handle: Optional[str]
    channelUrl: Optional[str]
    description: Optional[str]
    subscriberCount: Optional[float]
    subscriberCountText: Optional[str]
    videoCount: Optional[float]
    videoCountText: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    isVerified: bool
    country: Optional[str]
    joinedDate: Optional[str]
    thumbnails: List[Thumbnail]
    banners: List[Thumbnail]
    links: Optional[List[ChannelLink]]


class ChannelVideo(TypedDict, total=False):
    id: str
    type: Literal["video"]
    title: Optional[str]
    videoUrl: str
    author: Optional[str]
    authorId: Optional[str]
    duration: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    isLive: bool
    isUpcoming: bool
    upcomingAt: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    thumbnails: List[Thumbnail]


class ChannelShort(TypedDict, total=False):
    id: str
    type: Literal["short"]
    shortUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    thumbnails: List[Thumbnail]


class ChannelPlaylist(TypedDict, total=False):
    id: str
    type: Literal["playlist"]
    playlistUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    videoCount: Optional[str]
    thumbnails: List[Thumbnail]


ContentItem = Union[ChannelVideo, ChannelShort, ChannelPlaylist]


class ChannelData(TypedDict, total=False):
    channel: Optional[ChannelProfile]
    tab: Literal["video", "short", "playlist", "about"]
    items: List[ContentItem]
    continuationToken: Optional[str]
    empty: EmptyState


# --- playlist -------------------------------------------------------------
class PlaylistMeta(TypedDict, total=False):
    id: str
    type: Literal["playlist"]
    playlistUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    description: Optional[str]
    videoCount: Optional[str]
    thumbnails: List[Thumbnail]


class PlaylistItem(TypedDict, total=False):
    id: str
    type: Literal["video"]
    videoUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    duration: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    index: Optional[float]
    isLive: bool
    isPlayable: bool
    isUpcoming: bool
    upcomingAt: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    thumbnails: List[Thumbnail]


class PlaylistData(TypedDict, total=False):
    playlist: Optional[PlaylistMeta]
    items: List[PlaylistItem]
    continuationToken: Optional[str]
    empty: EmptyState


# --- suggest / account ----------------------------------------------------
class SuggestData(TypedDict, total=False):
    q: str
    hl: str
    gl: str
    suggestions: List[str]


class CreditsData(TypedDict, total=False):
    credits: int


class LogEntry(TypedDict, total=False):
    id: str
    userId: str
    apiKeyId: Optional[str]
    apiKeyName: Optional[str]
    endpoint: str
    method: str
    status: int
    credits: int
    durationMs: Optional[float]
    response: Optional[str]
    createdAt: str


class LogsData(TypedDict, total=False):
    logs: List[LogEntry]
    total: int
    page: int
    pageSize: int
    totalPages: int
    endpoints: List[str]


class UsageItem(TypedDict, total=False):
    date: str
    credits: int
    requests: int


class UsageData(TypedDict, total=False):
    items: List[UsageItem]


# --- response envelopes ---------------------------------------------------
class _Envelope(TypedDict, total=False):
    success: bool
    requestId: str
    cacheState: CacheState
    creditsUsed: int
    creditsRemaining: int


class _AccountEnvelope(TypedDict, total=False):
    success: bool
    requestId: str


class VideoResponse(_Envelope, total=False):
    data: VideoData


class VideoDetailsResponse(_Envelope, total=False):
    data: VideoDetailsData


class TranscriptResponse(_Envelope, total=False):
    data: TranscriptResult


class CommentsResponse(_Envelope, total=False):
    data: CommentsData


class LiveChatResponse(_Envelope, total=False):
    data: LiveChatData


class SearchResponse(_Envelope, total=False):
    data: SearchData


class ChannelResponse(_Envelope, total=False):
    data: ChannelData


class PlaylistResponse(_Envelope, total=False):
    data: PlaylistData


class SuggestResponse(_Envelope, total=False):
    data: SuggestData


class CreditsResponse(_AccountEnvelope, total=False):
    data: CreditsData


class LogsResponse(_AccountEnvelope, total=False):
    data: LogsData


class UsageResponse(_AccountEnvelope, total=False):
    data: UsageData
