"""Response types mirroring the Stophy OpenAPI schemas.

Guaranteed response keys are required. Values that YouTube does not always
provide are represented as ``Optional`` rather than making the key optional.
"""

from __future__ import annotations

from typing import List, Literal, Optional, TypedDict, Union

CacheState = Literal["hit", "miss"]
ErrorCode = Literal[
    "UNAUTHORIZED",
    "INSUFFICIENT_CREDITS",
    "BAD_REQUEST",
    "INVALID_INPUT",
    "NOT_FOUND",
    "CONCURRENCY_LIMITED",
    "UPSTREAM_UNAVAILABLE",
    "INTERNAL_ERROR",
]
LiveChatStatus = Literal["live", "upcoming", "replay", "chat_disabled", "not_live"]


class Thumbnail(TypedDict):
    url: str
    width: int
    height: int


class EmptyState(TypedDict):
    code: str
    message: str


# --- transcript -----------------------------------------------------------
class TranscriptLanguage(TypedDict):
    code: Optional[str]
    name: Optional[str]
    isAutoGenerated: bool


class TranscriptSegment(TypedDict):
    start: float
    duration: float
    text: str


class TranscriptTrack(TypedDict):
    languageCode: str
    languageName: str
    isAutoGenerated: bool


class TranscriptResult(TypedDict):
    videoId: str
    language: TranscriptLanguage
    segments: List[TranscriptSegment]
    text: str
    isTranslated: bool
    availableTracks: List[TranscriptTrack]


# --- video details --------------------------------------------------------
class Chapter(TypedDict):
    title: str
    startMs: float
    startSec: float


class VideoDetails(TypedDict):
    id: str
    type: Literal["video"]
    url: str
    videoUrl: str
    title: str
    author: Optional[str]
    authorId: Optional[str]
    category: Optional[str]
    description: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    isLive: bool
    likeCount: Optional[float]
    likeCountText: Optional[str]
    publishedAt: Optional[str]
    tags: List[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    thumbnails: List[Thumbnail]
    chapters: List[Chapter]


class RelatedVideo(TypedDict):
    id: str
    type: Literal["video"]
    url: str
    videoUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    thumbnails: List[Thumbnail]


class VideoDetailsData(TypedDict):
    videoId: str
    video: VideoDetails
    related: List[RelatedVideo]


# --- comments / replies ---------------------------------------------------
class Comment(TypedDict):
    id: str
    text: str
    author: Optional[str]
    authorId: Optional[str]
    authorThumbnail: Optional[str]
    hasChannelOwnerReplied: bool
    isChannelOwner: bool
    isHearted: bool
    isPinned: bool
    isVerified: bool
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    likeCount: Optional[float]
    likeCountText: Optional[str]
    replyCount: Optional[float]
    replyCountText: Optional[str]
    repliesToken: Optional[str]


class CommentsData(TypedDict):
    videoId: str
    sortBy: Literal["any", "latest", "top"]
    items: List[Comment]
    continuationToken: Optional[str]
    hasMore: bool


class Reply(TypedDict):
    id: str
    text: str
    author: Optional[str]
    authorId: Optional[str]
    authorThumbnail: Optional[str]
    hasChannelOwnerReplied: bool
    isChannelOwner: bool
    isHearted: bool
    isPinned: bool
    isVerified: bool
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    likeCount: Optional[float]
    likeCountText: Optional[str]


class RepliesData(TypedDict):
    items: List[Reply]
    continuationToken: Optional[str]
    hasMore: bool


# --- live chat ------------------------------------------------------------
class LiveChatMessage(TypedDict):
    id: str
    text: str
    author: Optional[str]
    authorId: Optional[str]
    timestampUsec: Optional[str]
    isOwner: bool
    isModerator: bool
    isVerified: bool
    superChatAmount: Optional[str]
    superChatCurrency: Optional[str]


class LiveChatData(TypedDict):
    videoId: str
    status: LiveChatStatus
    isLive: bool
    concurrentViewers: Optional[float]
    pollIntervalMs: Optional[float]
    messages: List[LiveChatMessage]
    continuationToken: Optional[str]
    hasMore: bool


VideoData = Union[VideoDetailsData, TranscriptResult, CommentsData, RepliesData, LiveChatData]


# --- search ---------------------------------------------------------------
class SearchVideo(TypedDict):
    type: Literal["video"]
    id: str
    videoUrl: str
    title: str
    author: Optional[str]
    authorId: Optional[str]
    description: Optional[str]
    duration: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    isLive: bool
    isUpcoming: bool
    isVerified: bool
    viewCount: Optional[float]
    viewCountText: Optional[str]
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    thumbnails: List[Thumbnail]


class SearchShort(TypedDict):
    type: Literal["short"]
    id: str
    shortUrl: str
    title: str
    viewCount: Optional[float]
    viewCountText: Optional[str]
    thumbnails: List[Thumbnail]


class SearchPlaylist(TypedDict):
    type: Literal["playlist"]
    id: str
    playlistUrl: str
    title: str
    author: Optional[str]
    authorId: Optional[str]
    videoCount: Optional[float]
    videoCountText: Optional[str]
    thumbnails: List[Thumbnail]


class SearchChannel(TypedDict):
    type: Literal["channel"]
    id: str
    channelUrl: str
    name: str
    handle: Optional[str]
    description: Optional[str]
    subscriberCount: Optional[float]
    subscriberCountText: Optional[str]
    isVerified: bool
    thumbnails: List[Thumbnail]


SearchItem = Union[SearchVideo, SearchShort, SearchPlaylist, SearchChannel]


class SearchQuery(TypedDict):
    q: str
    type: Literal["video", "short", "channel", "playlist", "movie"]
    sortBy: Literal["relevance", "popularity", "date", "rating"]
    uploadDate: Literal["today", "week", "month", "year"]
    duration: Literal["short", "medium", "long"]
    features: List[str]


class SearchData(TypedDict):
    items: List[SearchItem]
    continuationToken: Optional[str]
    hasMore: bool
    estimatedResults: Optional[int]


# --- channel --------------------------------------------------------------
class ChannelLink(TypedDict):
    title: str
    url: str


class ChannelProfile(TypedDict):
    type: Literal["channel"]
    id: Optional[str]
    url: Optional[str]
    name: Optional[str]
    handle: Optional[str]
    channelUrl: Optional[str]
    description: Optional[str]
    subscriberCount: Optional[float]
    subscriberCountText: Optional[str]
    videoCount: Optional[float]
    videoCountText: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    isVerified: bool
    country: Optional[str]
    joinedDate: Optional[str]
    thumbnails: List[Thumbnail]
    banners: List[Thumbnail]
    links: Optional[List[ChannelLink]]


class ChannelVideo(TypedDict):
    id: str
    type: Literal["video"]
    url: str
    title: Optional[str]
    videoUrl: str
    author: Optional[str]
    authorId: Optional[str]
    duration: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    isLive: bool
    isUpcoming: bool
    upcomingAt: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    thumbnails: List[Thumbnail]


class ChannelShort(TypedDict):
    id: str
    type: Literal["short"]
    url: str
    shortUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    thumbnails: List[Thumbnail]


class ChannelPlaylist(TypedDict):
    id: str
    type: Literal["playlist"]
    url: str
    playlistUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    videoCount: Optional[float]
    videoCountText: Optional[str]
    thumbnails: List[Thumbnail]


class ChannelPostVideo(TypedDict):
    id: str
    title: Optional[str]
    url: str


class ChannelPost(TypedDict):
    id: str
    type: Literal["post"]
    url: str
    content: Optional[str]
    publishedTimeText: Optional[str]
    likeCountText: Optional[str]
    commentCountText: Optional[str]
    images: List[dict[str, List[Thumbnail]]]
    video: Optional[ChannelPostVideo]


class ChannelCourse(ChannelPlaylist):
    type: Literal["course"]
    courseUrl: str


ContentItem = Union[ChannelVideo, ChannelShort, ChannelPlaylist, ChannelPost, ChannelCourse]


class ChannelData(TypedDict):
    channel: Optional[ChannelProfile]
    tab: Literal["video", "short", "playlist", "live", "post", "community", "course", "about"]
    items: List[ContentItem]
    continuationToken: Optional[str]
    hasMore: bool


# --- playlist -------------------------------------------------------------
class PlaylistMeta(TypedDict):
    id: str
    type: Literal["playlist"]
    url: str
    playlistUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    description: Optional[str]
    videoCount: Optional[float]
    videoCountText: Optional[str]
    thumbnails: List[Thumbnail]


class PlaylistItem(TypedDict):
    id: str
    type: Literal["video"]
    url: str
    videoUrl: str
    title: Optional[str]
    author: Optional[str]
    authorId: Optional[str]
    duration: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    index: Optional[float]
    isLive: bool
    isPlayable: bool
    isUpcoming: bool
    upcomingAt: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    thumbnails: List[Thumbnail]


class PlaylistData(TypedDict):
    playlist: Optional[PlaylistMeta]
    items: List[PlaylistItem]
    continuationToken: Optional[str]
    hasMore: bool


# --- music ---------------------------------------------------------------
class MusicArtistRef(TypedDict):
    id: Optional[str]
    name: str


class MusicAlbumRef(TypedDict):
    id: Optional[str]
    name: str


class MusicItem(TypedDict):
    type: Literal["song", "video", "album", "artist", "playlist", "podcast", "episode", "profile"]
    id: Optional[str]
    url: Optional[str]
    title: str
    author: Optional[str]
    authorId: Optional[str]
    album: Optional[MusicAlbumRef]
    artists: List[MusicArtistRef]
    duration: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    isExplicit: bool
    plays: Optional[str]
    thumbnails: List[Thumbnail]


class MusicSong(MusicItem):
    id: str
    url: str
    videoUrl: str
    lyricsBrowseId: Optional[str]
    relatedBrowseId: Optional[str]


class MusicSearchData(TypedDict):
    items: List[MusicItem]
    continuationToken: Optional[str]
    hasMore: bool


class MusicSuggestData(TypedDict):
    q: str
    suggestions: List[str]


class MusicSongData(TypedDict):
    song: MusicSong


class MusicEmptyData(TypedDict):
    empty: EmptyState


class MusicLyricsData(TypedDict):
    videoId: str
    videoUrl: str
    lyrics: Optional[str]
    source: Optional[str]
    hasTimedLyrics: bool


class MusicAlbum(TypedDict):
    id: str
    url: Optional[str]
    albumUrl: Optional[str]
    title: str
    artists: List[MusicArtistRef]
    year: Optional[str]
    trackCountText: Optional[str]
    durationText: Optional[str]
    thumbnails: List[Thumbnail]


class MusicAlbumData(TypedDict):
    album: MusicAlbum
    items: List[MusicItem]


class MusicArtist(TypedDict):
    id: Optional[str]
    url: Optional[str]
    channelUrl: Optional[str]
    name: str
    description: Optional[str]
    subscriberText: Optional[str]
    thumbnails: List[Thumbnail]


class MusicArtistSectionItem(TypedDict):
    id: Optional[str]
    url: Optional[str]
    kind: Literal["watch", "browse"]
    title: str
    subtitle: Optional[str]
    thumbnails: List[Thumbnail]


class MusicArtistSection(TypedDict):
    title: str
    items: List[MusicArtistSectionItem]


class MusicArtistData(TypedDict):
    artist: MusicArtist
    sections: List[MusicArtistSection]


class MusicPlaylist(TypedDict):
    id: Optional[str]
    url: Optional[str]
    playlistUrl: Optional[str]
    title: str
    subtitle: Optional[str]
    trackCountText: Optional[str]
    durationText: Optional[str]
    thumbnails: List[Thumbnail]


class MusicPlaylistData(TypedDict):
    playlist: MusicPlaylist
    items: List[MusicItem]
    continuationToken: Optional[str]
    hasMore: bool


MusicData = Union[
    MusicSearchData,
    MusicSuggestData,
    MusicSongData,
    MusicEmptyData,
    MusicLyricsData,
    MusicAlbumData,
    MusicArtistData,
    MusicPlaylistData,
]


# --- kids ----------------------------------------------------------------
class KidsVideoItem(TypedDict):
    type: Literal["video"]
    id: str
    url: str
    videoUrl: str
    kidsUrl: str
    title: str
    author: Optional[str]
    authorId: Optional[str]
    authorUrl: Optional[str]
    duration: Optional[str]
    durationSec: Optional[float]
    durationText: Optional[str]
    publishedAt: Optional[str]
    publishedAtText: Optional[str]
    viewCount: Optional[float]
    viewCountText: Optional[str]
    thumbnails: List[Thumbnail]


class KidsVideoDetails(KidsVideoItem):
    description: Optional[str]
    isLive: bool
    isLiveContent: bool
    keywords: List[str]


class KidsSearchData(TypedDict):
    items: List[KidsVideoItem]
    continuationToken: Optional[str]
    hasMore: bool


class KidsVideoData(TypedDict):
    video: KidsVideoDetails
    related: List[KidsVideoItem]


KidsData = Union[KidsSearchData, KidsVideoData, MusicEmptyData]


# --- suggest / account ----------------------------------------------------
class SuggestData(TypedDict):
    suggestions: List[str]


class CreditsData(TypedDict):
    credits: int


class LogEntry(TypedDict):
    id: str
    userId: str
    apiKeyId: Optional[str]
    apiKeyName: Optional[str]
    endpoint: str
    method: str
    status: int
    credits: int
    durationMs: Optional[float]
    response: Optional[str]
    createdAt: str


class LogsData(TypedDict):
    logs: List[LogEntry]
    total: int
    page: int
    pageSize: int
    totalPages: int
    endpoints: List[str]


class UsageItem(TypedDict):
    date: str
    credits: int
    requests: int


class UsageData(TypedDict):
    items: List[UsageItem]


# --- response envelopes ---------------------------------------------------
class _Envelope(TypedDict):
    success: bool
    requestId: str
    cacheState: CacheState
    creditsUsed: int
    creditsRemaining: int


class _AccountEnvelope(TypedDict):
    success: bool
    requestId: str


class VideoResponse(_Envelope):
    data: VideoData


class VideoDetailsResponse(_Envelope):
    data: VideoDetailsData


class TranscriptResponse(_Envelope):
    data: TranscriptResult


class CommentsResponse(_Envelope):
    data: CommentsData


class RepliesResponse(_Envelope):
    data: RepliesData


class LiveChatResponse(_Envelope):
    data: LiveChatData


class SearchResponse(_Envelope):
    data: SearchData


class ChannelResponse(_Envelope):
    data: ChannelData


class PlaylistResponse(_Envelope):
    data: PlaylistData


class SuggestResponse(_Envelope):
    data: SuggestData


class MusicResponse(_Envelope):
    data: MusicData


class KidsResponse(_Envelope):
    data: KidsData


class CreditsResponse(_AccountEnvelope):
    data: CreditsData


class LogsResponse(_AccountEnvelope):
    data: LogsData


class UsageResponse(_AccountEnvelope):
    data: UsageData
