// Builds the namespaced client surface from openapi.json and the hey-api types.
// Usage: bun scripts/gen-surface.ts

const ALIASES: Record<string, string> = {
	"/v1/web/search": "/v1/google/search",
	"/v1/web/news": "/v1/google/news",
};

const root = new URL("..", import.meta.url);
const specUrl = new URL("openapi.json", root);
const typesUrl = new URL(
	"packages/typescript/src/generated/types.gen.ts",
	root,
);
const outUrl = new URL(
	"packages/typescript/src/generated/surface.gen.ts",
	root,
);

const spec: unknown = JSON.parse(await Bun.file(specUrl).text());
const types = await Bun.file(typesUrl).text();
const operations = operationsFrom(spec);

for (const operation of operations) {
	const name = pascal(operation.id);
	if (
		operation.method === "post" &&
		!types.includes(`export type ${name}Data =`)
	) {
		throw new Error(
			`Generated types are missing ${name}Data. Run openapi-ts first.`,
		);
	}
	if (!types.includes(`export type ${name}Response =`)) {
		throw new Error(
			`Generated types are missing ${name}Response. Run openapi-ts first.`,
		);
	}
}

const typeNames = new Set<string>();
for (const operation of operations) {
	const name = pascal(operation.id);
	typeNames.add(`${name}Response`);
	if (operation.method === "post") typeNames.add(`${name}Data`);
}

const tree = buildTree(operations);
const lines = [
	"// Generated by scripts/gen-surface.ts. Do not edit.",
	"",
	'import { get, post, postOptional } from "../bind";',
	"import type {",
	...[...typeNames].sort().map((name) => `\t${name},`),
	'} from "./types.gen";',
	'import type { Caller } from "../transport";',
	"",
	"export function bindSurface(call: Caller) {",
	"\treturn {",
	...emitObject(tree, 2),
	"\t};",
	"}",
	"",
	"export type Surface = ReturnType<typeof bindSurface>;",
	"",
];

await Bun.write(outUrl, lines.join("\n"));
console.log(`Wrote ${operations.length} operations to ${outUrl.pathname}.`);

interface Operation {
	id: string;
	method: "get" | "post";
	path: string;
	optionalBody: boolean;
	segments: string[];
}

interface Node {
	children: Map<string, Node>;
	operation?: Operation;
}

function operationsFrom(value: unknown): Operation[] {
	if (!isRecord(value) || !isRecord(value.paths)) {
		throw new Error("OpenAPI document has no paths.");
	}
	const operations: Operation[] = [];
	for (const [path, item] of Object.entries(value.paths)) {
		if (!isRecord(item)) continue;
		if (isRecord(item.get))
			operations.push(operationFrom(path, "get", item.get));
		if (isRecord(item.post))
			operations.push(operationFrom(path, "post", item.post));
	}
	for (const [alias, target] of Object.entries(ALIASES)) {
		const original = operations.find((operation) => operation.path === target);
		if (original === undefined) continue;
		operations.push({ ...original, path: alias, segments: segmentsOf(alias) });
	}
	return operations;
}

function segmentsOf(path: string): string[] {
	return path
		.split("/")
		.filter((segment) => segment.length > 0 && segment !== "v1");
}

function operationFrom(
	path: string,
	method: "get" | "post",
	operation: Record<string, unknown>,
): Operation {
	if (typeof operation.operationId !== "string") {
		throw new Error(`${method.toUpperCase()} ${path} is missing operationId.`);
	}
	const segments = segmentsOf(path);
	if (segments.length === 0) throw new Error(`Cannot namespace ${path}.`);
	return {
		id: operation.operationId,
		method,
		path,
		optionalBody: method === "post" && requiredFields(operation).length === 0,
		segments,
	};
}

function requiredFields(operation: Record<string, unknown>): string[] {
	const body = operation.requestBody;
	if (!isRecord(body) || !isRecord(body.content)) return [];
	const json = body.content["application/json"];
	if (!isRecord(json)) return [];
	return requiredIn(json.schema);
}

function requiredIn(schema: unknown): string[] {
	if (!isRecord(schema)) return [];
	const branches = schema.oneOf ?? schema.anyOf;
	if (Array.isArray(branches)) return branches.flatMap(requiredIn);
	if (!Array.isArray(schema.required)) return [];
	return schema.required.filter(
		(item): item is string => typeof item === "string",
	);
}

function buildTree(operations: Operation[]): Node {
	const root: Node = { children: new Map() };
	for (const operation of operations) {
		let node = root;
		for (const segment of operation.segments) {
			const child = node.children.get(segment) ?? { children: new Map() };
			node.children.set(segment, child);
			node = child;
		}
		node.operation = operation;
	}
	return root;
}

function emitObject(node: Node, depth: number): string[] {
	const pad = "\t".repeat(depth);
	const lines: string[] = [];
	for (const [name, child] of node.children) {
		lines.push(`${pad}${name}: ${emitValue(child, depth)},`);
	}
	return lines;
}

function emitValue(node: Node, depth: number): string {
	const call = node.operation ? emitCall(node.operation) : undefined;
	if (!call) {
		return `{\n${emitObject(node, depth + 1).join("\n")}\n${"\t".repeat(depth)}}`;
	}
	if (node.children.size === 0) return call;
	const fields = emitObject(node, depth + 2).join("\n");
	return `Object.assign(${call}, {\n${fields}\n${"\t".repeat(depth + 1)}})`;
}

function emitCall(operation: Operation): string {
	const name = pascal(operation.id);
	if (operation.method === "get")
		return `get<${name}Response>(${JSON.stringify(operation.path)}, call)`;
	const fn = operation.optionalBody ? "postOptional" : "post";
	return `${fn}<${name}Data["body"], ${name}Response>(${JSON.stringify(operation.path)}, call)`;
}

function pascal(operationId: string): string {
	return operationId.charAt(0).toUpperCase() + operationId.slice(1);
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}
